//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BoggleModel.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Localization {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Localization() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BoggleModel.Properties.Localization", typeof(Localization).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to G-O-L-D-O-B.
        /// </summary>
        public static string dice1 {
            get {
                return ResourceManager.GetString("dice1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ch-O-O-E-E-N.
        /// </summary>
        public static string dice10 {
            get {
                return ResourceManager.GetString("dice10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to J-I-R-F-S-E.
        /// </summary>
        public static string dice11 {
            get {
                return ResourceManager.GetString("dice11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to R-Z-S-P-L-T.
        /// </summary>
        public static string dice12 {
            get {
                return ResourceManager.GetString("dice12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to R-E-S-D-A-H.
        /// </summary>
        public static string dice13 {
            get {
                return ResourceManager.GetString("dice13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to V-U-E-C-P-D.
        /// </summary>
        public static string dice14 {
            get {
                return ResourceManager.GetString("dice14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to T-A-P-S-C-A.
        /// </summary>
        public static string dice15 {
            get {
                return ResourceManager.GetString("dice15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to T-M-O-F-I-U.
        /// </summary>
        public static string dice16 {
            get {
                return ResourceManager.GetString("dice16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to F-U-A-A-B-R.
        /// </summary>
        public static string dice2 {
            get {
                return ResourceManager.GetString("dice2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to B-T-A-I-N-A.
        /// </summary>
        public static string dice3 {
            get {
                return ResourceManager.GetString("dice3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to B-U-O-A-E-I.
        /// </summary>
        public static string dice4 {
            get {
                return ResourceManager.GetString("dice4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to V-U-Q-D-Ch-B.
        /// </summary>
        public static string dice5 {
            get {
                return ResourceManager.GetString("dice5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to T-A-I-O-L-E.
        /// </summary>
        public static string dice6 {
            get {
                return ResourceManager.GetString("dice6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to M-I-B-N-E-E.
        /// </summary>
        public static string dice7 {
            get {
                return ResourceManager.GetString("dice7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C-M-R-E-A-E.
        /// </summary>
        public static string dice8 {
            get {
                return ResourceManager.GetString("dice8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A-X-N-H-S-J.
        /// </summary>
        public static string dice9 {
            get {
                return ResourceManager.GetString("dice9", resourceCulture);
            }
        }
    }
}
